function gphoto_getall(self)
  % gphoto_getall get all configuration values
  if strncmp(self.port, 'sim',3)
    if isempty(self.settings)
      self.settings = gphoto_getall_sim(self);
    end
    return
  end
  
  self.proc.stdout = '';
  write(self.proc, sprintf('list-config\n'));
  self.expect{end+1} = { 'post_getconfig', self};

end % gphoto_getall

% ---------------------------------------------------------------------------
function config = gphoto_getall_sim(self)
  % an output from https://github.com/gphoto/gphoto2/issues/149
  % camera was: Canon EOS M100
  message = { '/main/actions/manualfocusdrive', ...
    'Label: Drive Canon DSLR Manual focus', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: None', ...
    'Choice: 0 Near 1', ...
    'Choice: 1 Near 2', ...
    'Choice: 2 Near 3', ...
    'Choice: 3 None', ...
    'Choice: 4 Far 1', ...
    'Choice: 5 Far 2', ...
    'Choice: 6 Far 3', ...
    'END', ...
    '/main/actions/cancelautofocus', ...
    'Label: Cancel Canon DSLR Autofocus', ...
    'Readonly: 0', ...
    'Type: TOGGLE', ...
    'Current: 0', ...
    'END', ...
    '/main/actions/opcode', ...
    'Label: PTP Opcode', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 0x1001,0xparam1,0xparam2', ...
    'END', ...
    '/main/settings/output', ...
    'Label: Camera Output', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: Unknown value 0008', ...
    'Choice: 0 Off', ...
    'Choice: 1 Unknown value 0008', ...
    'END', ...
    '/main/settings/evfmode', ...
    'Label: EVF Mode', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: 1', ...
    'Choice: 0 1', ...
    'END', ...
    '/main/settings/depthoffield', ...
    'Label: Depth of Field', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 0', ...
    'END', ...
    '/main/settings/capturetarget', ...
    'Label: Capture Target', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: Internal RAM', ...
    'Choice: 0 Internal RAM', ...
    'Choice: 1 Memory card', ...
    'END', ...
    '/main/settings/capture', ...
    'Label: Capture', ...
    'Readonly: 0', ...
    'Type: TOGGLE', ...
    'Current: 0', ...
    'END', ...
    '/main/status/serialnumber', ...
    'Label: Serial Number', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 916714BD8CD54497814E54F77E68FB90', ...
    'END', ...
    '/main/status/manufacturer', ...
    'Label: Camera Manufacturer', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: Canon Inc.', ...
    'END', ...
    '/main/status/cameramodel', ...
    'Label: Camera Model', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: Canon EOS M100 (simulated)', ...
    'END', ...
    '/main/status/deviceversion', ...
    'Label: Device Version', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 3-15.0.1.0', ...
    'END', ...
    '/main/status/vendorextension', ...
    'Label: Vendor Extension', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: None', ...
    'END', ...
    '/main/status/model', ...
    'Label: Camera Model', ...
    'Readonly: 1', ...
    'Type: TEXT', ...
    'Current: Canon EOS M100 (simulated)', ...
    'END', ...
    '/main/status/firmwareversion', ...
    'Label: Firmware Version', ...
    'Readonly: 1', ...
    'Type: TEXT', ...
    'Current: 1.0.0.0', ...
    'END', ...
    '/main/status/batterylevel', ...
    'Label: Battery Level', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 100%', ...
    'END', ...
    '/main/status/lensname', ...
    'Label: Lens Name', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: EF-M15-45mm f/3.5-6.3 IS STM', ...
    'END', ...
    '/main/status/eosserialnumber', ...
    'Label: Serial Number', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 633050004249', ...
    'END', ...
    '/main/status/availableshots', ...
    'Label: Available Shots', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 770', ...
    'END', ...
    '/main/imgsettings/imageformat', ...
    'Label: Image Format', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: Medium Fine JPEG', ...
    'Choice: 0 Medium Fine JPEG', ...
    'END', ...
    '/main/imgsettings/iso', ...
    'Label: ISO Speed', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: Auto', ...
    'Choice: 0 Auto', ...
    'Choice: 1 100', ...
    'Choice: 2 125', ...
    'Choice: 3 160', ...
    'Choice: 4 200', ...
    'Choice: 5 250', ...
    'Choice: 6 320', ...
    'Choice: 7 400', ...
    'Choice: 8 500', ...
    'Choice: 9 640', ...
    'Choice: 10 800', ...
    'Choice: 11 1000', ...
    'Choice: 12 1250', ...
    'Choice: 13 1600', ...
    'Choice: 14 2000', ...
    'Choice: 15 2500', ...
    'Choice: 16 3200', ...
    'Choice: 17 4000', ...
    'Choice: 18 5000', ...
    'Choice: 19 6400', ...
    'Choice: 20 8000', ...
    'Choice: 21 10000', ...
    'Choice: 22 12800', ...
    'Choice: 23 16000', ...
    'Choice: 24 20000', ...
    'Choice: 25 25600', ...
    'END', ...
    '/main/capturesettings/exposurecompensation', ...
    'Label: Exposure Compensation', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: 0', ...
    'Choice: 0 -3', ...
    'Choice: 1 -2.6', ...
    'Choice: 2 -2.3', ...
    'Choice: 3 -2', ...
    'Choice: 4 -1.6', ...
    'Choice: 5 -1.3', ...
    'Choice: 6 -1', ...
    'Choice: 7 -0.6', ...
    'Choice: 8 -0.3', ...
    'Choice: 9 0', ...
    'Choice: 10 0.3', ...
    'Choice: 11 0.6', ...
    'Choice: 12 1', ...
    'Choice: 13 1.3', ...
    'Choice: 14 1.6', ...
    'Choice: 15 2', ...
    'Choice: 16 2.3', ...
    'Choice: 17 2.6', ...
    'Choice: 18 3', ...
    'END', ...
    '/main/capturesettings/focusmode', ...
    'Label: Focus Mode', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: One Shot', ...
    'Choice: 0 One Shot', ...
    'END', ...
    '/main/capturesettings/continuousaf', ...
    'Label: Continuous AF', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: On', ...
    'Choice: 0 Off', ...
    'Choice: 1 On', ...
    'END', ...
    '/main/capturesettings/aspectratio', ...
    'Label: Aspect Ratio', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: 3:2', ...
    'Choice: 0 3:2', ...
    'END', ...
    '/main/capturesettings/storageid', ...
    'Label: Storage Device', ...
    'Readonly: 0', ...
    'Type: TEXT', ...
    'Current: 00010001', ...
    'END', ...
    '/main/capturesettings/autoexposuremode', ...
    'Label: Canon Auto Exposure Mode', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: P', ...
    'Choice: 0 P', ...
    'Choice: 1 TV', ...
    'Choice: 2 AV', ...
    'Choice: 3 Manual', ...
    'Choice: 4 Bulb', ...
    'Choice: 5 A_DEP', ...
    'Choice: 6 DEP', ...
    'Choice: 7 Custom', ...
    'Choice: 8 Lock', ...
    'Choice: 9 Green', ...
    'Choice: 10 Night Portrait', ...
    'Choice: 11 Sports', ...
    'Choice: 12 Portrait', ...
    'Choice: 13 Landscape', ...
    'Choice: 14 Closeup', ...
    'Choice: 15 Flash Off', ...
    'END', ...
    '/main/capturesettings/drivemode', ...
    'Label: Drive Mode', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: Single', ...
    'Choice: 0 Single', ...
    'Choice: 1 Continuous', ...
    'Choice: 2 Timer 10 sec', ...
    'Choice: 3 Timer 2 sec', ...
    'END', ...
    '/main/capturesettings/aperture', ...
    'Label: Aperture', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: implicit auto', ...
    'Choice: 0 implicit auto', ...
    'END', ...
    '/main/capturesettings/shutterspeed', ...
    'Label: Shutter Speed', ...
    'Readonly: 0', ...
    'Type: RADIO', ...
    'Current: auto', ...
    'Choice: 0 auto', ...
    'END' };
  config = gphoto_parse_output(self, message);
end % gphoto_getall_sim
